### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by cyanwolfg** [hardcore-sushi/AIRA-android#1]
Hi, I'm kind of curious and I found this repository coming from the DroidFS one, I like the idea of this application and I find it useful to communicate between my own devices.

I am not a developer but I will try to help at least with the spanish translation and reporting bugs or giving ideas about the app.

Since I don't know how to add a new language and I only know how to suggest modifications since the translation is uploaded I will share here the file with the translation.
[strings-es.zip](https://github.com/hardcore-sushi/AIRA-android/files/8642530/strings-es.zip)

**Comment by hardcore-sushi** [comment]
Thank you very much for your contribution! I added your Spanish translation: 81dc567ff0fcdc8384de73d8d6dc6b903e3368ca
